package com.jgz.config.server.config.mapper;

import com.jgz.config.server.config.model.Config;
import com.jgz.config.server.config.model.ConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int countByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int deleteByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    List<Config> selectByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    Config selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int updateByExample(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_config
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    int updateByPrimaryKey(Config record);
}