package com.jgz.config.server.config.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.access_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private String accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.group_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.config_name
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.config_key
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.config_value
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_config.remark
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.id
     *
     * @return the value of t_config.id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.id
     *
     * @param id the value for t_config.id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.access_id
     *
     * @return the value of t_config.access_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.access_id
     *
     * @param accessId the value for t_config.access_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId == null ? null : accessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.group_id
     *
     * @return the value of t_config.group_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.group_id
     *
     * @param groupId the value for t_config.group_id
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.config_name
     *
     * @return the value of t_config.config_name
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.config_name
     *
     * @param configName the value for t_config.config_name
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.config_key
     *
     * @return the value of t_config.config_key
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.config_key
     *
     * @param configKey the value for t_config.config_key
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.config_value
     *
     * @return the value of t_config.config_value
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.config_value
     *
     * @param configValue the value for t_config.config_value
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_config.remark
     *
     * @return the value of t_config.remark
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_config.remark
     *
     * @param remark the value for t_config.remark
     *
     * @mbggenerated Wed Mar 09 21:16:10 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}